<?php
session_start();
header('Content-Type: application/json; charset=utf-8');
// The frontend and PHP API are served from the same Apache origin, so CORS is not required.
$host='127.0.0.1';
$user='root';
$password='';
$db='charity_platform';

$conn=new mysqli($host,$user,$password,$db);
if($conn->connect_error){http_response_code(500);echo json_encode(['success'=>false,'message'=>'Database connection failed. Start XAMPP MySQL and import database.sql.']);exit;}
$conn->set_charset('utf8mb4');
$action=$_GET['action']??''; $input=json_decode(file_get_contents('php://input'),true)?:$_POST;
function out($data=[], $msg='OK'){echo json_encode(['success'=>true,'message'=>$msg,'data'=>$data]);exit;}
function fail($msg,$code=400){http_response_code($code);echo json_encode(['success'=>false,'message'=>$msg]);exit;}
function clean($v){return trim((string)($v??''));}
function require_login(){if(empty($_SESSION['user_id']))fail('Please log in first.',401);}
function require_admin(){if(empty($_SESSION['user_id'])||($_SESSION['role']??'')!=='admin')fail('Admin access required.',403);}
function rows($r){$a=[];while($x=$r->fetch_assoc())$a[]=$x;return $a;}

if($action==='session') out(['logged_in'=>!empty($_SESSION['user_id']),'user'=>empty($_SESSION['user_id'])?null:['id'=>$_SESSION['user_id'],'name'=>$_SESSION['name'],'email'=>$_SESSION['email'],'role'=>$_SESSION['role']]]);
if($action==='logout'){session_unset();session_destroy();out([], 'Logged out');}
if($action==='register'){$name=clean($input['name']);$email=clean($input['email']);$password=$input['password']??'';$phone=clean($input['phone']);if($name===''||$email===''||strlen($password)<6)fail('Name, valid email and password of at least 6 characters are required.');$hash=password_hash($password,PASSWORD_DEFAULT);$st=$conn->prepare('INSERT INTO users(name,email,password,phone) VALUES(?,?,?,?)');$st->bind_param('ssss',$name,$email,$hash,$phone);if(!$st->execute())fail($st->errno===1062?'Email already registered.':'Registration failed.');$_SESSION['user_id']=$st->insert_id;$_SESSION['name']=$name;$_SESSION['email']=$email;$_SESSION['role']='donor';out([],'Account created');}
if($action==='login'){$email=clean($input['email']);$password=$input['password']??'';$st=$conn->prepare('SELECT * FROM users WHERE email=? LIMIT 1');$st->bind_param('s',$email);$st->execute();$u=$st->get_result()->fetch_assoc();if(!$u||!password_verify($password,$u['password']))fail('Invalid email or password.',401);$_SESSION['user_id']=$u['id'];$_SESSION['name']=$u['name'];$_SESSION['email']=$u['email'];$_SESSION['role']=$u['role'];out(['user'=>['id'=>$u['id'],'name'=>$u['name'],'email'=>$u['email'],'role'=>$u['role']]],'Logged in');}
if($action==='home'){$d=[];$d['active_campaigns']=$conn->query("SELECT COUNT(*) c FROM campaigns WHERE status='ongoing'")->fetch_assoc()['c'];$d['total_raised']=$conn->query('SELECT COALESCE(SUM(amount),0) c FROM donations')->fetch_assoc()['c'];$d['donation_count']=$conn->query('SELECT COUNT(*) c FROM donations')->fetch_assoc()['c'];$d['volunteer_count']=$conn->query('SELECT COUNT(*) c FROM volunteers')->fetch_assoc()['c'];$d['donor_count']=$conn->query('SELECT COUNT(DISTINCT COALESCE(user_id,donor_name)) c FROM donations')->fetch_assoc()['c'];$d['project_count']=$conn->query('SELECT COUNT(*) c FROM campaigns')->fetch_assoc()['c'];$d['campaigns']=rows($conn->query("SELECT * FROM campaigns WHERE status='ongoing' ORDER BY created_at DESC LIMIT 3"));$d['news']=rows($conn->query('SELECT * FROM news ORDER BY date DESC LIMIT 3'));out($d);}
if($action==='campaigns'){$where=[];$params=[];$types='';foreach([['q','(title LIKE ? OR description LIKE ?)'],['category','category=?'],['status','status=?']] as [$k,$cond]){if(($v=clean($input[$k]??$_GET[$k]??''))!==''){if($k==='q'){$where[]=$cond;$like="%$v%";$params=[$like,$like];$types='ss';}else{$where[]=$cond;$params[]=$v;$types.='s';}}}$sql='SELECT * FROM campaigns'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY status="ongoing" DESC, created_at DESC';$st=$conn->prepare($sql);
if($params)$st->bind_param($types,...$params);
$st->execute();
$campaigns=rows($st->get_result());               // fetch BEFORE the next query
$cats=rows($conn->query('SELECT DISTINCT category FROM campaigns ORDER BY category'));
out(['campaigns'=>$campaigns,'categories'=>$cats]);}
if($action==='campaign'){$id=(int)($input['id']??$_GET['id']??0);$st=$conn->prepare('SELECT * FROM campaigns WHERE id=?');$st->bind_param('i',$id);$st->execute();$c=$st->get_result()->fetch_assoc();if(!$c)fail('Campaign not found.',404);$st=$conn->prepare('SELECT donor_name,amount,anonymous,date FROM donations WHERE campaign_id=? ORDER BY date DESC LIMIT 6');$st->bind_param('i',$id);$st->execute();$c['recent']=rows($st->get_result());$st=$conn->prepare('SELECT COUNT(*) c FROM donations WHERE campaign_id=?');$st->bind_param('i',$id);$st->execute();$c['donor_count']=$st->get_result()->fetch_assoc()['c'];$c['days_left']=$c['end_date']?max(0,(int)((strtotime($c['end_date'])-time())/86400)):null;out($c);}
if($action==='donate'){$campaign=(int)$input['campaign_id'];$amount=(float)$input['amount'];$name=clean($input['donor_name']);$frequency=$input['frequency']??'one-time';$method=clean($input['payment_method']);$anonymous=!empty($input['anonymous'])?1:0;$dedication=clean($input['dedication']);if($amount<=0||$name==='')fail('Donor name and a valid amount are required.');$st=$conn->prepare("SELECT id,status FROM campaigns WHERE id=?");$st->bind_param('i',$campaign);$st->execute();$c=$st->get_result()->fetch_assoc();if(!$c||$c['status']!=='ongoing')fail('This campaign is not accepting donations.');$uid=$_SESSION['user_id']??null;$st=$conn->prepare('INSERT INTO donations(user_id,campaign_id,donor_name,amount,frequency,payment_method,anonymous,dedication) VALUES(?,?,?,?,?,?,?,?)');$st->bind_param('iisdssis',$uid,$campaign,$name,$amount,$frequency,$method,$anonymous,$dedication);if(!$st->execute())fail('Donation could not be recorded.');$id=$st->insert_id;$st=$conn->prepare('UPDATE campaigns SET raised_amount=raised_amount+? WHERE id=?');$st->bind_param('di',$amount,$campaign);$st->execute();out(['id'=>$id],'Donation recorded');}
if($action==='dashboard'){require_login();$st=$conn->prepare('SELECT COALESCE(SUM(amount),0) total,COUNT(*) c FROM donations WHERE user_id=?');$st->bind_param('i',$_SESSION['user_id']);$st->execute();$tot=$st->get_result()->fetch_assoc();$st=$conn->prepare('SELECT d.*,c.title campaign_title FROM donations d JOIN campaigns c ON c.id=d.campaign_id WHERE d.user_id=? ORDER BY d.date DESC');$st->bind_param('i',$_SESSION['user_id']);$st->execute();out(['total_donated'=>$tot['total'],'donation_count'=>$tot['c'],'donations'=>rows($st->get_result())]);}
if($action==='receipt'){require_login();$id=(int)($input['id']??$_GET['id']??0);$st=$conn->prepare('SELECT d.*,c.title campaign_title FROM donations d JOIN campaigns c ON c.id=d.campaign_id WHERE d.id=? AND (d.user_id=? OR ?=1)');$admin=$_SESSION['role']==='admin'?1:0;$st->bind_param('iii',$id,$_SESSION['user_id'],$admin);$st->execute();$r=$st->get_result()->fetch_assoc();if(!$r)fail('Receipt not found.',404);out($r);}
if($action==='blood'){$st=$conn->prepare('INSERT INTO blood_donors(name,blood_group,phone,city,last_donation_date) VALUES(?,?,?,?,?)');$a=clean($input['name']);$b=clean($input['blood_group']);$p=clean($input['phone']);$c=clean($input['city']);$l=clean($input['last_donation_date'])?:null;$st->bind_param('sssss',$a,$b,$p,$c,$l);if(!$st->execute())fail('Could not register donor.');out();}
if($action==='volunteer'){$st=$conn->prepare('INSERT INTO volunteers(name,email,phone,city,skills,availability,experience) VALUES(?,?,?,?,?,?,?)');$v=[];foreach(['name','email','phone','city','skills','availability','experience'] as $k)$v[]=clean($input[$k]);$st->bind_param('sssssss',...$v);if(!$st->execute())fail('Could not submit volunteer application.');out();}
if($action==='contact'){$st=$conn->prepare('INSERT INTO contact_messages(name,email,message) VALUES(?,?,?)');$a=clean($input['name']);$b=clean($input['email']);$c=clean($input['message']);$st->bind_param('sss',$a,$b,$c);if(!$st->execute())fail('Could not send message.');out();}
if($action==='news')out(rows($conn->query('SELECT * FROM news ORDER BY date DESC')));
if(str_starts_with($action,'admin_')){require_admin();if($action==='admin_dashboard'){$d=['users'=>$conn->query('SELECT COUNT(*) c FROM users')->fetch_assoc()['c'],'campaigns'=>$conn->query('SELECT COUNT(*) c FROM campaigns')->fetch_assoc()['c'],'donations'=>$conn->query('SELECT COALESCE(SUM(amount),0) c FROM donations')->fetch_assoc()['c'],'volunteers'=>$conn->query('SELECT COUNT(*) c FROM volunteers')->fetch_assoc()['c']];out($d);}if($action==='admin_campaigns')out(rows($conn->query('SELECT * FROM campaigns ORDER BY created_at DESC')));if($action==='admin_donations')out(rows($conn->query('SELECT d.*,c.title campaign_title FROM donations d JOIN campaigns c ON c.id=d.campaign_id ORDER BY d.date DESC')));if($action==='admin_users')out(rows($conn->query('SELECT id,name,email,phone,role,created_at FROM users ORDER BY created_at DESC')));if($action==='admin_blood')out(rows($conn->query('SELECT * FROM blood_donors ORDER BY created_at DESC')));if($action==='admin_volunteers')out(rows($conn->query('SELECT * FROM volunteers ORDER BY created_at DESC')));if($action==='admin_news'){$title=clean($input['title']);$desc=clean($input['description']);if($title==='')fail('Title required.');$st=$conn->prepare('INSERT INTO news(title,description) VALUES(?,?)');$st->bind_param('ss',$title,$desc);$st->execute();out();}if($action==='admin_messages')out(rows($conn->query('SELECT * FROM contact_messages ORDER BY date DESC')));if($action==='admin_volunteer_status'){$id=(int)$input['id'];$status=$input['status']==='approved'?'approved':'rejected';$st=$conn->prepare('UPDATE volunteers SET status=? WHERE id=?');$st->bind_param('si',$status,$id);$st->execute();out();}if($action==='admin_delete'){$id=(int)$input['id'];$map=['campaign'=>'DELETE FROM campaigns WHERE id=?','donation'=>'DELETE FROM donations WHERE id=?','news'=>'DELETE FROM news WHERE id=?','message'=>'DELETE FROM contact_messages WHERE id=?'];$type=$input['type']??'';if(!isset($map[$type]))fail('Invalid delete type.');$st=$conn->prepare($map[$type]);$st->bind_param('i',$id);$st->execute();out();}}
fail('Unknown action.',404);
?>